## M3 T01
### Sprint 3. 
**Programació numèrica, dataframes i anàlisi estadístic**

### - Exercici 1

Crea una funció que donat un Array d’una dimensió, et faci un resum estadístic bàsic de les dades. Si detecta que l’array té més d’una dimensió, ha de mostrar un missatge d’error.

In [8]:
import numpy as np  # importem NumPy fent servir np com el seu alias
import pandas as pd # importem Pandas fent servir pd com el seu alias

def crear_array():
    '''Aquesta funció serveix per crear una array que pot ser 1-D o 2-D, de forma aleatoria. 
    Dos de cada 3 casos tindrà 1D, l\'altre serà de 2D'''
    xD = np.random.randint(3)
    if xD >= 1:
        return np.random.randint(1000,size=(10))
    else:
        pass

    return np.random.randint(1000,size=(10,10))

array = crear_array()
dimensions = array.ndim
print('El array creat es: ',array)
print('i te ',dimensions,'-D dimensions')


El array creat es:  [346 510 236 847 321 131 759 733 405   7]
i te  1 -D dimensions


In [9]:
# Resum estadístic fent servir NumPy. Es fa servir la array generada a dalt 
import numpy as np  # importem NumPy fent servir np com el seu alias

def estad_amb_numpy():
    if  array.ndim == 1:
        '''Aquesta funció ha estat creada amb les funcions de NumPy per diferents estadístics 
        descriptius. Al següent cuadre de codi es fa el mateix fent servir Pandas'''
        array_max = np.amax(array)
        array_min = np.amin(array)
        array_range = np.ptp(array)
        array_mitja = np.mean(array)
        array_mediana = np.nanmedian(array)
        array_desv_estand = np.std(array)
        array_1_quartil = np.percentile(array, 25)
        array_2_quartil = np.percentile(array, 50)
        array_3_quartil = np.percentile(array, 75)
        array_1_decil = np.percentile(array, 10)
        array_9_decil = np.percentile(array, 90)
        estats_array =(['Màxim:','Minim','Range','Mitja','Mediana','Desviació estàndar',
                        '1er quartil','2on quartil','3er quartil','1er decil','9e decil'],
                   [array_max,array_min,array_range,array_mitja,array_mediana,array_desv_estand,
                    array_1_quartil,array_2_quartil,array_3_quartil,array_1_decil,array_9_decil])
    
        estats_array2 = np.transpose(estats_array) # Faig una transposició per que es vegi més clar
        return estats_array2
    else:
        print('Error, l\'array te 2 dimensions. Torna a correr la funció crear_array() per tal d\'obtenir una array d\'una dimensió' )
    

estad_amb_numpy()


array([['Màxim:', '847'],
       ['Minim', '7'],
       ['Range', '840'],
       ['Mitja', '429.5'],
       ['Mediana', '375.5'],
       ['Desviació estàndar', '265.6811058393125'],
       ['1er quartil', '257.25'],
       ['2on quartil', '375.5'],
       ['3er quartil', '677.25'],
       ['1er decil', '118.60000000000001'],
       ['9e decil', '767.8']], dtype='<U32')

In [10]:
import numpy as np  # importem NumPy fent servir np com el seu alias
import pandas as pd # importem Pandas fent servir pd com el seu alias

def resum_estadistic():
    '''Aquesta funcio serveix per produir un resum estadístic fent servir pandas'''
    if array.ndim == 1:
        array_describe = pd.DataFrame(array)
        return array_describe.describe()
    else:
        print('Error, l\'array te 2 dimensions')

estadistica = resum_estadistic()
estadistica

0
count   10.000000
mean   429.500000
std    280.052475
min      7.000000
25%    257.250000
50%    375.500000
75%    677.250000
max    847.000000

### - Exercici 2

Crea una funció que et generi un quadrat NxN de nombres aleatoris entre el 0 i el 100.

In [11]:
import numpy as np  # importem NumPy fent servir np com el seu alias
from numpy import random

def quadrat():
    '''Aquesta funcio serveix per definit un cuadrat de NxN (sent N un numero aleatori entre 5 i 10)
    i que tingui numeros entre 0 i 100'''
    nxn = random.randint(5,11)
    return random.randint(100,size=(nxn,nxn))
    
quadrat()


array([[27, 54, 53, 88, 10, 14, 21, 98, 40],
       [61, 85, 65, 51, 60, 77, 50, 15, 19],
       [ 6, 76, 81,  1, 85, 47, 54, 88, 10],
       [18,  0, 70, 57, 87, 78, 84, 28, 21],
       [89, 14, 31, 78, 71, 78, 61,  3, 47],
       [31, 15, 94, 31, 50, 14, 48, 37,  3],
       [99,  0, 91, 87, 81, 52, 87, 39, 37],
       [10, 25, 80, 57, 59, 31, 45, 36,  2],
       [12, 78, 69, 13, 31, 92, 77, 10, 22]])

### - Exercici 3

Crea una funció que donada una taula de dues dimensions (NxM), et calculi els totals per fila i els totals per columna.

In [12]:
import numpy as np  # importem NumPy fent servir np com el seu alias
from numpy import random

def quadrat2():
    '''Aquesta funcio serveix per definit un cuadrat de NxM 
    (sent N i M numeros aleatoris entre 5 i 10 i 10 i 15, respectivament)
    i que tingui numeros entre 0 i 100'''
    llarg_n = random.randint(5,11)
    ample_m = random.randint(10,16)
    return random.randint(100,size=(llarg_n,ample_m))
    
print('La array es: \n',quadrat2())
print('La suma de totes les columnes es: ',np.nansum(quadrat2(), axis=0))
print('La suma de totes les files es: ',np.nansum(quadrat2(), axis=1))

La array es: 
 [[34 49 90 92 68 27  5 34  5 43 54 70 57 10 67]
 [55 42 15 38 66 34 38 51  7 64  8 88 78 12 71]
 [40 39 15 63 28 49 58 45 10 91 81  7 63 84 14]
 [54 57 78 23 33 88 53 19 63 84 32  0 40 97  9]
 [81 37 91 45 33 81 72 17 82 24 54  3 75 65 28]
 [27 12 18 64 18 17 91 55 64 42  7 56 76 70 50]
 [24 72 55 70 87 72 61 14 87 36 61 30  9 80 51]
 [90 91 18 42 46 62 58 69 54 25 74 25 11 72 42]
 [21 69 45 64  3 91 33 62 34 63 77 86 53  6 80]
 [18 78 97 78  9 47 24 67 39 83 22 56 65 21 33]]
La suma de totes les columnes es:  [ 88 429 317 248 322 313 225 239 216 348 306 297]
La suma de totes les files es:  [532 550 809 580 781 434]


### - Exercici 4

Implementa manualment una funció que calculi el coeficient de correlació. Informa-te'n sobre els seus usos i interpretació.

In [14]:
import numpy as np  # importem NumPy fent servir np com el seu alias

print(np.corrcoef(quadrat())) # crido la funció quadrat() definida previament

# El coeficient de correlacio agafa valors entre 1 (correlació positiva perfecte) i 
# -1 (correlació negativa perfecte). Si el coeficient de correlació es proper a 0
# vol dir que no existeiz cap correlació entre les variables.'''

[[ 1.          0.72229289  0.46802696 -0.23271408 -0.26880913  0.30454775
   0.03197612  0.18589084  0.20195945]
 [ 0.72229289  1.          0.57611901 -0.30611269 -0.32536919  0.03730977
   0.04285151  0.19944992 -0.14617759]
 [ 0.46802696  0.57611901  1.         -0.61470249 -0.67803559  0.0987082
   0.50145905 -0.28686223 -0.06010656]
 [-0.23271408 -0.30611269 -0.61470249  1.          0.8446744  -0.34963625
  -0.24772769 -0.11176021 -0.12247794]
 [-0.26880913 -0.32536919 -0.67803559  0.8446744   1.         -0.13155805
  -0.322372    0.12724155  0.02601756]
 [ 0.30454775  0.03730977  0.0987082  -0.34963625 -0.13155805  1.
  -0.44828447 -0.18167473 -0.03375535]
 [ 0.03197612  0.04285151  0.50145905 -0.24772769 -0.322372   -0.44828447
   1.          0.21534565 -0.17898393]
 [ 0.18589084  0.19944992 -0.28686223 -0.11176021  0.12724155 -0.18167473
   0.21534565  1.          0.04457264]
 [ 0.20195945 -0.14617759 -0.06010656 -0.12247794  0.02601756 -0.03375535
  -0.17898393  0.04457264  1.  